<?php
// ─── Regenerate illustration via Gemini ──────────────────────────────────────
// POST {exercise_id, prompt} → generates new illustration, upserts to DB
header('Content-Type: application/json');
header('Access-Control-Allow-Origin: *');
header('Access-Control-Allow-Methods: POST, OPTIONS');
header('Access-Control-Allow-Headers: Content-Type, Authorization');

if ($_SERVER['REQUEST_METHOD'] === 'OPTIONS') { http_response_code(204); exit; }
if ($_SERVER['REQUEST_METHOD'] !== 'POST') {
    http_response_code(405); echo json_encode(['error' => 'Method not allowed']); exit;
}

define('DB_HOST', '%%DB_HOST%%');
define('DB_NAME', '%%DB_NAME%%');
define('DB_USER', '%%DB_USER%%');
define('DB_PASS', '%%DB_PASS%%');

try {
    $pdo = new PDO(
        'mysql:host='.DB_HOST.';dbname='.DB_NAME.';charset=utf8mb4',
        DB_USER, DB_PASS,
        [PDO::ATTR_ERRMODE => PDO::ERRMODE_EXCEPTION]
    );
} catch (Exception $e) {
    http_response_code(500); echo json_encode(['error' => 'DB connection failed']); exit;
}

require_once __DIR__ . '/fb_auth_check.php';
require_auth($pdo);

if (!function_exists('str_starts_with')) {
    function str_starts_with($haystack, $needle) {
        return strncmp($haystack, $needle, strlen($needle)) === 0;
    }
}

// ─── Gemini config ───────────────────────────────────────────────────────────
$configFile = __DIR__ . '/config.local.php';
if (file_exists($configFile)) { require_once $configFile; }
if (!defined('GEMINI_API_KEY')) {
    $envKey = getenv('GEMINI_API_KEY');
    if ($envKey) define('GEMINI_API_KEY', $envKey);
    else { http_response_code(500); echo json_encode(['error' => 'Gemini API key not configured']); exit; }
}

$GEMINI_MODEL = 'gemini-2.5-flash-image';

// ─── Standard style suffix ───────────────────────────────────────────────────
$STYLE_SUFFIX = "The figure has a simple, minimal design with solid color fills (teal/cyan sports bra and dark gray/navy leggings), no facial details, light skin tone, brown hair in a ponytail. Clean geometric body proportions, no outlines, soft flat shading. Fitness app UI style, consistent character design across all poses. No text, no background elements, no shadows on the ground.";

// ─── Parse request ───────────────────────────────────────────────────────────
$data = json_decode(file_get_contents('php://input'), true);
if (!$data) { http_response_code(400); echo json_encode(['error' => 'Invalid JSON']); exit; }

$exerciseId = trim($data['exercise_id'] ?? '');
$prompt     = trim($data['prompt'] ?? '');

if (!$exerciseId || !$prompt) {
    http_response_code(400); echo json_encode(['error' => 'exercise_id and prompt required']); exit;
}

// Append standard style if not already present
if (stripos($prompt, 'teal') === false && stripos($prompt, 'sports bra') === false) {
    $prompt .= "\n\n" . $STYLE_SUFFIX;
}

// ─── Call Gemini API ─────────────────────────────────────────────────────────
$url = "https://generativelanguage.googleapis.com/v1beta/models/{$GEMINI_MODEL}:generateContent?key=" . GEMINI_API_KEY;

$payload = [
    'contents' => [
        ['parts' => [['text' => $prompt]]]
    ],
    'generationConfig' => [
        'responseModalities' => ['image', 'text'],
    ]
];

$ch = curl_init($url);
curl_setopt_array($ch, [
    CURLOPT_POST           => true,
    CURLOPT_POSTFIELDS     => json_encode($payload),
    CURLOPT_HTTPHEADER     => ['Content-Type: application/json'],
    CURLOPT_RETURNTRANSFER => true,
    CURLOPT_TIMEOUT        => 120,
]);
$response = curl_exec($ch);
$httpCode = curl_getinfo($ch, CURLINFO_HTTP_CODE);
$curlErr  = curl_error($ch);
curl_close($ch);

if ($curlErr) {
    http_response_code(502); echo json_encode(['error' => 'Gemini request failed: ' . $curlErr]); exit;
}
if ($httpCode !== 200) {
    http_response_code(502); echo json_encode(['error' => 'Gemini returned HTTP ' . $httpCode, 'detail' => json_decode($response, true)]); exit;
}

$result = json_decode($response, true);
$parts  = $result['candidates'][0]['content']['parts'] ?? [];

// Find image part
$imageData = null;
$mimeType  = 'image/png';
foreach ($parts as $part) {
    if (isset($part['inlineData']['mimeType']) && str_starts_with($part['inlineData']['mimeType'], 'image/')) {
        $imageData = $part['inlineData']['data'];
        $mimeType  = $part['inlineData']['mimeType'];
        break;
    }
}

if (!$imageData) {
    http_response_code(502); echo json_encode(['error' => 'No image generated by Gemini']); exit;
}

// ─── Upsert to DB ───────────────────────────────────────────────────────────
$stmt = $pdo->prepare(
    "INSERT INTO exercise_illustrations (exercise_id, frame_number, image_base64, mime_type, prompt_used)
     VALUES (?, 1, ?, ?, ?)
     ON DUPLICATE KEY UPDATE image_base64=VALUES(image_base64), mime_type=VALUES(mime_type),
                             prompt_used=VALUES(prompt_used), updated_at=NOW()"
);
$stmt->execute([$exerciseId, $imageData, $mimeType, $prompt]);

echo json_encode([
    'success'      => true,
    'exercise_id'  => $exerciseId,
    'image_base64' => $imageData,
    'mime_type'     => $mimeType,
]);
